### ISSUE TITLE
Add E gene builds

### ISSUE THREAD

**Issue by j23414** [nextstrain/dengue#17]
### Context

By user request:

>  Is there any chance we could get a E gene build of nextstrain dengue? Much more sequences of E than full genome, especially in some parts of the world

### Possible steps to a solution

1. Pull out E gene sequence from the [dengue reference.gb file](https://github.com/nextstrain/dengue/blob/f513d319055c706a11370b76a95fdad729edc1cc/config/reference_dengue_all.gb#L55-L58) to be used as the reference for the E gene builds.
  a. Or follow [rsv rules](https://github.com/nextstrain/rsv/blob/fd6f5dcaa46e52e364fdb0ccbb356e6de87b4290/workflow/snakemake_rules/core.smk#L23-L42)
2. Add a filter_length_per_group function for “all_E”, “denv1_E”, “denv2_E”, etc similar to [filter_sequences_per_group](https://github.com/nextstrain/dengue/blob/f513d319055c706a11370b76a95fdad729edc1cc/Snakefile#L28-L36).
3. Add E to the dropdown under “Dataset” by appending `_E` and `_genome` (e.g. `dengue_denv1_genome.json` and `dengue_denv1_E.json` and updating the [nextstrain.org manifest file](https://github.com/nextstrain/nextstrain.org/blob/8fbf3de13697447aa158fb9eeba43bf5f2a84f03/data/manifest_core.json). 

### Dependencies

* https://github.com/nextstrain/dengue/issues/19
* https://github.com/nextstrain/dengue/pull/16

**Comment by joverlee521** [comment]
For posterity, the workflow changes are on the [phlogenetic_dir_E branch](https://github.com/nextstrain/dengue/compare/phylogenetic_dir...phylogenetic_dir_E).

**Comment by j23414** [comment]
Explore adding `{gene}_coverage` metadata columns for any gene/locus of interest using Nextclade, taking inspiration from the following RSV script:

* [rsv/ingest/bin/extend-metadata.py](https://github.com/nextstrain/rsv/blob/1df2377cd9c5882dc1a853075b5e7ca0565b040d/ingest/bin/extend-metadata.py)

**Comment by ammaraziz** [comment]
I'm that annoying user. Thank you so much for the E tree, it's been super helpful.

**Comment by j23414** [comment]
Closed as completed since the following PRs are merged:

* https://github.com/nextstrain/dengue/pull/47
* https://github.com/nextstrain/dengue/pull/48
