### ISSUE TITLE
Update the links of FASTA and metadata in the README

### ISSUE THREAD

**Issue by Rohit-Satyam** [nextstrain/dengue#52]
@j23414 Can you please update the link of the FASTA files and metadata in the README [here](https://github.com/nextstrain/dengue/tree/main/phylogenetic) with the links you provided in issue comment [here](https://github.com/nextstrain/dengue/issues/28#issuecomment-1969993406). I usually go to the phylogenetic/README.md file to download the most updated metadata and sequences.

**Comment by j23414** [comment]
Thanks for flagging! Will be fixed soon after I merge https://github.com/nextstrain/dengue/pull/53, I'm just waiting for CI checks to complete.
