### ISSUE TITLE
Outliers in the Dengue Dataset

### ISSUE THREAD

**Issue by Rohit-Satyam** [nextstrain/dengue#83]
The following Accessions were found as the outlier sequences by [Hill et al 2024](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11426435/) in her recent publication (The list below is the courtesy of `Suraj Jagtap` on the paper. These sequences were found to emanate from re sequencing of commonly used virus stocks.

@j23414 Do you guys plan to retain them or remove them. Kindly let me know (I see that there are some nextclade people on the paper).

```
MW828678.1
MT076932.1
MT076933.1
MT076934.1
MT076935.1
MK506262.1
KU094071.1
KM204119.1
EU848545.1
MZ284953.1
MZ285732.1
MF576311.1
MW945433.1
MT076937.1
MH613984.1
MH613985.1
MH613986.1
MK506264.1
MK506263.1
KU094070.1
KM204118.1
KF704358.1
KF704357.1
KF704354.1
KF704355.1
KJ918750.1
KF704356.1
HQ891023.1
HQ891024.1
GQ398268.1
FJ906959.1
FJ390389.1
EU854293.1
MZ285058.1
KY586699.1
OP809583.1
LT996912.1
MT076948.1
MK506265.1
JN697379.1
KM190936.1
MW793460.1
MT076955.1
KY586824.1
KY586825.1
MW793459.1
KY586823.1
KY586826.1
MK506266.1

```

**Comment by j23414** [comment]
Hi @Rohit-Satyam! Would you feel comfortable submitting a PR to remove these outliers from the live build? Mostly it involves adding them to this exclude list

* https://github.com/nextstrain/dengue/blob/main/phylogenetic/config/exclude.txt

We usually leave off the version number (e.g. `MK506266.1` -> `MK506266`) and add a comment on reasoning, for line example:

```
MK506266 # Outlier according to publication Hill et al, 2024 (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11426435/)
```

**Comment by Rohit-Satyam** [comment]
Okay @j23414 . I see 9 of them are already there. So I will add rest 40 of the accessions

**Comment by j23414** [comment]
Thanks @Rohit-Satyam ! Closing this since https://github.com/nextstrain/dengue/pull/84 merged
